# Generated by Django 5.0.2 on 2024-06-04 11:05

import blog.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('breweryId', models.CharField(max_length=120)),
                ('userName', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=60, validators=[blog.models.validate_min_length])),
                ('description', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(50, 'The description must be atleast 50 characters long.')])),
                ('rate', models.IntegerField(validators=[blog.models.validate_rating])),
                ('check_field', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('breweryId', 'userId')},
            },
        ),
    ]
