# Generated by Django 5.0.2 on 2024-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('breweryId', models.CharField(max_length=120)),
                ('userName', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=500)),
                ('stars', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
