# Generated by Django 5.0.2 on 2024-06-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='title',
        ),
    ]
