# Generated by Django 5.0.2 on 2024-06-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]
    '''

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='stars',
            new_name='rate',
        ),
    ]
'''