# Generated by Django 5.0.2 on 2024-06-07 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_userreview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='description',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(50, 'Your review must be atleast 50 characters long.')]),
        ),
    ]
