# Generated by Django 5.0.2 on 2024-06-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_stars_userreview_rate'),
        ('blog', '0003_alter_userreview_description'),
    ]

    operations = [
    ]
